spring.application.name=evaluation-service
server.port=8083
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/netflix}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:netflix}
