spring.application.name=movie-service
server.port=8081
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://teste:2430@cluster0-lakoi.mongodb.net/test?retryWrites=true&w=majority}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:netflix}
